export const GetUsers = () => {
   return [
    {
      "id": 503340608,
      "nombre": "Marco",
      "apellido": "López",
      "apellido2": "Alvarado",
      "email": "",
      "puntoVenta": "Tilarán",
      "telefono": "7299-6821",
      "certificados": ["1", "2"],
      "areaCovertura": "Tilarán",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "Guanacaste",
      "canton": "Liberia",
      "distrito": "Liberia",
      "especializacion": ["Const. Liviana", "Repellos y pisos"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 502490950,
      "nombre": "Luis",
      "apellido": "Alvarado",
      "apellido2": "Rodriguez",
      "email": "",
      "puntoVenta": "Tilarán",
      "telefono": "8582-2890",
      "certificados": ["1", "3"],
      "areaCovertura": "Tilarán",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "Guanacaste",
      "canton": "Liberia",
      "distrito": "Liberia",
      "especializacion": ["Repellos y pisos", "Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 503860699,
      "nombre": "Kender",
      "apellido": "Castro",
      "apellido2": "Bravo",
      "email": "",
      "puntoVenta": "Tilarán",
      "telefono": "8824-0783",
      "certificados": ["1", "2", "3"],
      "areaCovertura": "Tilarán",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "Guanacaste",
      "canton": "Liberia",
      "distrito": "Liberia",
      "especializacion": ["Const. Liviana", "Repellos y pisos", "Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 501830193,
      "nombre": "Álvaro",
      "apellido": "Segura",
      "apellido2": "Sánchez",
      "email": "",
      "puntoVenta": "Tilarán",
      "telefono": "8375-2207",
      "certificados": ["3"],
      "areaCovertura": "Tilarán",
      "areaTrabajo": ["Pintura"],
      "provincia": "Guanacaste",
      "canton": "Liberia",
      "distrito": "Liberia",
      "especializacion": ["Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 503290920,
      "nombre": "Minor",
      "apellido": "Solano",
      "apellido2": "Paniagua",
      "email": "",
      "puntoVenta": "Tilarán",
      "telefono": "7051-9779",
      "certificados": ["1"],
      "areaCovertura": "Tilarán",
      "areaTrabajo": ["Construcción"],
      "provincia": "Guanacaste",
      "canton": "Liberia",
      "distrito": "Liberia",
      "especializacion": ["Repellos y pisos"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 503850643,
      "nombre": "Marlon",
      "apellido": "Salas",
      "apellido2": "Murillo",
      "email": "",
      "puntoVenta": "Tilarán",
      "telefono": "8696-9106",
      "certificados": ["3"],
      "areaCovertura": "Tilarán",
      "areaTrabajo": ["Construcción"],
      "provincia": "Guanacaste",
      "canton": "Liberia",
      "distrito": "Liberia",
      "especializacion": ["Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 205120268,
      "nombre": "Cesar",
      "apellido": "Arias",
      "apellido2": "Cambronero",
      "email": "",
      "puntoVenta": "Tilarán",
      "telefono": "8605-3438",
      "certificados": ["2", "3"],
      "areaCovertura": "Tilarán",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "Guanacaste",
      "canton": "Liberia",
      "distrito": "Liberia",
      "especializacion": ["Const. Liviana", "Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 503340619,
      "nombre": "Jose",
      "apellido": "Rojas",
      "apellido2": "Herrera",
      "email": "",
      "puntoVenta": "Tilarán",
      "telefono": "8564-3532",
      "certificados": ["3"],
      "areaCovertura": "Tilarán",
      "areaTrabajo": ["Pintura"],
      "provincia": "Guanacaste",
      "canton": "Liberia",
      "distrito": "Liberia",
      "especializacion": ["Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 503610757,
      "nombre": "Felipe",
      "apellido": "Herrera",
      "apellido2": "Salas",
      "email": "",
      "puntoVenta": "Tilarán",
      "telefono": "6380-1387",
      "certificados": ["3"],
      "areaCovertura": "Tilarán",
      "areaTrabajo": ["Pintura"],
      "provincia": "Guanacaste",
      "canton": "Liberia",
      "distrito": "Liberia",
      "especializacion": ["Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 602640903,
      "nombre": "Carlos",
      "apellido": "Gonzalez",
      "apellido2": "Novo",
      "email": "",
      "puntoVenta": "Tilarán",
      "telefono": "8433-6546",
      "certificados": ["3"],
      "areaCovertura": "Tilarán",
      "areaTrabajo": ["Pintura"],
      "provincia": "Guanacaste",
      "canton": "Liberia",
      "distrito": "Liberia",
      "especializacion": ["Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 303490965,
      "nombre": "Nancy",
      "apellido": "Salazar",
      "apellido2": "Torres",
      "email": "",
      "puntoVenta": "Guápiles",
      "telefono": "8779-0164",
      "certificados": ["1", "2"],
      "areaCovertura": "Guápiles",
      "areaTrabajo": ["Construcción"],
      "provincia": "Limón",
      "canton": "Pococí",
      "distrito": "Jiménez",
      "especializacion": ["Const. Liviana", "Repellos y pisos"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 107640185,
      "nombre": "Aliana",
      "apellido": "Chaves",
      "apellido2": "Pérez",
      "email": "",
      "puntoVenta": "Guápiles",
      "telefono": "8421-0456",
      "certificados": ["1"],
      "areaCovertura": "Guápiles",
      "areaTrabajo": ["Construcción"],
      "provincia": "Limón",
      "canton": "Pococí",
      "distrito": "Guápiles",
      "especializacion": ["Repellos y pisos"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 303530341,
      "nombre": "Abraham",
      "apellido": "Ruiz",
      "apellido2": "Guzman",
      "email": "",
      "puntoVenta": "Oreamuno",
      "telefono": "8763-5914",
      "certificados": ["1"],
      "areaCovertura": "Oreamuno",
      "areaTrabajo": ["Construcción"],
      "provincia": "Cartago",
      "canton": "Cartago",
      "distrito": "",
      "especializacion": ["Repellos y pisos"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 303580546,
      "nombre": "Esteban",
      "apellido": "Gomez",
      "apellido2": "Meza",
      "email": "",
      "puntoVenta": "Oreamuno",
      "telefono": "8643-6377",
      "certificados": ["1", "2", "3"],
      "areaCovertura": "Oreamuno",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "Cartago",
      "canton": "Cartago",
      "distrito": "",
      "especializacion": ["Const. Liviana", "Repellos y pisos", "Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 302700402,
      "nombre": "Jose",
      "apellido": "Soto",
      "apellido2": "Pacheco",
      "email": "",
      "puntoVenta": "Oreamuno",
      "telefono": "8963-4431",
      "certificados": ["1"],
      "areaCovertura": "Oreamuno",
      "areaTrabajo": ["Construcción"],
      "provincia": "Cartago",
      "canton": "Cartago",
      "distrito": "",
      "especializacion": ["Repellos y pisos"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 304080502,
      "nombre": "Cristian",
      "apellido": "Fonseca",
      "apellido2": "Gomez",
      "email": "",
      "puntoVenta": "Oreamuno",
      "telefono": "6212-9862",
      "certificados": ["1"],
      "areaCovertura": "Oreamuno",
      "areaTrabajo": ["Construcción"],
      "provincia": "Cartago",
      "canton": "Cartago",
      "distrito": "",
      "especializacion": ["Repellos y pisos"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 302740564,
      "nombre": "Jorge",
      "apellido": "Gonzalez",
      "apellido2": "Maroto",
      "email": "",
      "puntoVenta": "Oreamuno",
      "telefono": "8922-1043",
      "certificados": ["1"],
      "areaCovertura": "Oreamuno",
      "areaTrabajo": ["Construcción"],
      "provincia": "Cartago",
      "canton": "Cartago",
      "distrito": "",
      "especializacion": ["Repellos y pisos"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 304110496,
      "nombre": "Luis Alfredo",
      "apellido": "Barquero",
      "apellido2": "Gonzalez",
      "email": "",
      "puntoVenta": "Oreamuno",
      "telefono": "7220-3797",
      "certificados": ["1", "2"],
      "areaCovertura": "Oreamuno",
      "areaTrabajo": ["Construcción"],
      "provincia": "Cartago",
      "canton": "Cartago",
      "distrito": "",
      "especializacion": ["Const. Liviana", "Repellos y pisos"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 304080425,
      "nombre": "David",
      "apellido": "Morales",
      "apellido2": "Tencio",
      "email": "",
      "puntoVenta": "Oreamuno",
      "telefono": "8797-7908",
      "certificados": ["1", "2"],
      "areaCovertura": "Oreamuno",
      "areaTrabajo": ["Construcción"],
      "provincia": "Cartago",
      "canton": "Cartago",
      "distrito": "",
      "especializacion": ["Const. Liviana", "Repellos y pisos"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 303500294,
      "nombre": "Oscar",
      "apellido": "Alfaro",
      "apellido2": "Cordoba",
      "email": "",
      "puntoVenta": "Oreamuno",
      "telefono": "8874-4788",
      "certificados": ["1", "3"],
      "areaCovertura": "Oreamuno",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "Cartago",
      "canton": "Cartago",
      "distrito": "",
      "especializacion": ["Repellos y pisos", "Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 304320222,
      "nombre": "Rodolfo",
      "apellido": "Rivera",
      "apellido2": "Gonzalez",
      "email": "",
      "puntoVenta": "Oreamuno",
      "telefono": "8328-8508",
      "certificados": ["1"],
      "areaCovertura": "Oreamuno",
      "areaTrabajo": ["Construcción"],
      "provincia": "Cartago",
      "canton": "Cartago",
      "distrito": "",
      "especializacion": ["Repellos y pisos"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 305350161,
      "nombre": "Esteban",
      "apellido": "Gómez",
      "apellido2": "Rivera",
      "email": "",
      "puntoVenta": "Oreamuno",
      "telefono": "6072-1746",
      "certificados": ["1", "3"],
      "areaCovertura": "Oreamuno",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "Cartago",
      "canton": "Cartago",
      "distrito": "",
      "especializacion": ["Repellos y pisos", "Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 109190610,
      "nombre": "Julio",
      "apellido": "Calvo",
      "apellido2": "Hidalgo",
      "email": "",
      "puntoVenta": "Pérez Zeledón",
      "telefono": "8721-4363",
      "certificados": ["1", "3"],
      "areaCovertura": "Pérez Zeledón",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "San José",
      "canton": "Pérez Zeledón",
      "distrito": "",
      "especializacion": ["Repellos y pisos", "Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 118680390,
      "nombre": "Alejandro",
      "apellido": "Calvo",
      "apellido2": "Navarro",
      "email": "",
      "puntoVenta": "Pérez Zeledón",
      "telefono": "8401-9264",
      "certificados": ["1", "3"],
      "areaCovertura": "Pérez Zeledón",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "San José",
      "canton": "Pérez Zeledón",
      "distrito": "",
      "especializacion": ["Repellos y pisos", "Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 700790424,
      "nombre": "William",
      "apellido": "Chinchilla",
      "apellido2": "Solis",
      "email": "",
      "puntoVenta": "Guácimo",
      "telefono": "8461-4991",
      "certificados": ["1", "3"],
      "areaCovertura": "Limón",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "Limón",
      "canton": "Guácimo",
      "distrito": "",
      "especializacion": ["Repellos y pisos", "Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 700810028,
      "nombre": "Wilber",
      "apellido": "Méndez",
      "apellido2": "Porta",
      "email": "",
      "puntoVenta": "Guácimo",
      "telefono": "6185-7772",
      "certificados": ["1", "2", "3"],
      "areaCovertura": "Limón",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "Limón",
      "canton": "Guácimo",
      "distrito": "",
      "especializacion": ["Const. Liviana", "Repellos y pisos", "Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 701180193,
      "nombre": "Cristian",
      "apellido": "Howard",
      "apellido2": "",
      "email": "",
      "puntoVenta": "Guácimo",
      "telefono": "8825-2465",
      "certificados": ["1", "3"],
      "areaCovertura": "Limón",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "Limón",
      "canton": "Guácimo",
      "distrito": "",
      "especializacion": ["Repellos y pisos", "Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 401720161,
      "nombre": "Luis",
      "apellido": "Castro",
      "apellido2": "Chavarría",
      "email": "",
      "puntoVenta": "Guácimo",
      "telefono": "8422-5580",
      "certificados": ["1", "2", "3"],
      "areaCovertura": "Limón",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "Limón",
      "canton": "Guácimo",
      "distrito": "",
      "especializacion": ["Const. Liviana", "Repellos y pisos", "Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 701080688,
      "nombre": "Jorge",
      "apellido": "Cedeño",
      "apellido2": "Torres",
      "email": "",
      "puntoVenta": "Guácimo",
      "telefono": "8632-4802",
      "certificados": ["1", "2", "3"],
      "areaCovertura": "Limón",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "Limón",
      "canton": "Guácimo",
      "distrito": "",
      "especializacion": ["Const. Liviana", "Repellos y pisos", "Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 204060103,
      "nombre": "Marvin",
      "apellido": "Sequiera",
      "apellido2": "Mena",
      "email": "",
      "puntoVenta": "Guácimo",
      "telefono": "8622-4943",
      "certificados": ["1", "2", "3"],
      "areaCovertura": "Limón",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "Limón",
      "canton": "Guácimo",
      "distrito": "",
      "especializacion": ["Const. Liviana", "Repellos y pisos", "Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 701930804,
      "nombre": "Josué",
      "apellido": "Peraza",
      "apellido2": "Aguilar",
      "email": "",
      "puntoVenta": "Guácimo",
      "telefono": "6040-8629",
      "certificados": ["1", "2", "3"],
      "areaCovertura": "Limón",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "Limón",
      "canton": "Guácimo",
      "distrito": "",
      "especializacion": ["Const. Liviana", "Repellos y pisos", "Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 110960051,
      "nombre": "Olman",
      "apellido": "Araya",
      "apellido2": "Ríos",
      "email": "",
      "puntoVenta": "Guácimo",
      "telefono": "8618-8463",
      "certificados": ["1", "2", "3"],
      "areaCovertura": "Limón",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "Limón",
      "canton": "Guácimo",
      "distrito": "",
      "especializacion": ["Const. Liviana", "Repellos y pisos", "Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 116230901,
      "nombre": "Ronny",
      "apellido": "Azofeifa",
      "apellido2": "Jiron",
      "email": "",
      "puntoVenta": "Guácimo",
      "telefono": "6471-4711",
      "certificados": ["1", "2", "3"],
      "areaCovertura": "Limón",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "Limón",
      "canton": "Guácimo",
      "distrito": "",
      "especializacion": ["Const. Liviana", "Repellos y pisos", "Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 702160036,
      "nombre": "Gerardo",
      "apellido": "Chinchilla",
      "apellido2": "Machado",
      "email": "",
      "puntoVenta": "Guácimo",
      "telefono": "7186-2532",
      "certificados": ["1", "2", "3"],
      "areaCovertura": "Limón",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "Limón",
      "canton": "Guácimo",
      "distrito": "",
      "especializacion": ["Const. Liviana", "Repellos y pisos", "Pintura general"],
      "estrellas": "",
      "activo": true
    },
    {
      "id": 700690234,
      "nombre": "Misael",
      "apellido": "Dávila",
      "apellido2": "Gudiel",
      "email": "",
      "puntoVenta": "Guácimo",
      "telefono": "7219-7799",
      "certificados": ["1", "2", "3"],
      "areaCovertura": "Limón",
      "areaTrabajo": ["Construcción", "Pintura"],
      "provincia": "Limón",
      "canton": "Guácimo",
      "distrito": "",
      "especializacion": ["Const. Liviana", "Repellos y pisos", "Pintura general"],
      "estrellas": "",
      "activo": true
    }
  ]
  
};
